shared:
    image: node:12

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - install: npm install
            - test: npm test

    publish:
        requires: main
        template: screwdriver-cd/semantic-release
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Pushing tags to Git
            - GH_TOKEN

    docker-trigger:
        requires: publish
        steps:
            - trigger: git clone https://github.com/screwdriver-cd/toolbox.git ci && ./ci/git-latest.sh && DOCKER_TAG=`cat VERSION` ./ci/docker-trigger.sh
        environment:
            # Docker hub repo
            DOCKER_REPO: screwdrivercd/buildcluster-queue-worker
        secrets:
            # Trigger a Docker Hub build
            - DOCKER_TRIGGER

    # Deploy to beta environment
    beta:
        requires: docker-trigger
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - get-tag: ./ci/git-latest.sh
            - wait-docker: DOCKER_TAG=`cat VERSION` ./ci/docker-wait.sh
            - deploy-k8s: K8S_TAG=`cat VERSION` ./ci/k8s-deploy.sh
            - test: echo Put acceptance tests here
        environment:
            DOCKER_REPO: screwdrivercd/buildcluster-queue-worker
            K8S_CONTAINER: screwdriver-buildcluster-queue-worker
            K8S_IMAGE: screwdrivercd/buildcluster-queue-worker
            K8S_HOST: kubernetes
            K8S_DEPLOYMENT: buildcluster-queue-worker-beta
        secrets:
            # Talking to Kubernetes
            - K8S_TOKEN

    # Deploy to our prod environment and run tests
    prod:
        requires: [beta]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - get-tag: ./ci/git-latest.sh
            - wait-docker: DOCKER_TAG=`cat VERSION` ./ci/docker-wait.sh
            - deploy-k8s: K8S_TAG=`cat VERSION` ./ci/k8s-deploy.sh
            - test: echo Put acceptance tests here
        environment:
            DOCKER_REPO: screwdrivercd/buildcluster-queue-worker
            K8S_CONTAINER: screwdriver-buildcluster-queue-worker
            K8S_IMAGE: screwdrivercd/buildcluster-queue-worker
            K8S_HOST: kubernetes
            K8S_DEPLOYMENT: buildcluster-queue-worker
        secrets:
            # Talking to Kubernetes
            - K8S_TOKEN

    # Deploy to our prod environment and run tests
    prod-bf1:
        requires: [beta]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - get-tag: ./ci/git-latest.sh
            - wait-docker: DOCKER_TAG=`cat VERSION` ./ci/docker-wait.sh
            - deploy-k8s: K8S_TAG=`cat VERSION` ./ci/k8s-deploy.sh
            - test: echo Put acceptance tests here
        environment:
            DOCKER_REPO: screwdrivercd/buildcluster-queue-worker
            K8S_CONTAINER: screwdriver-buildcluster-queue-worker
            K8S_IMAGE: screwdrivercd/buildcluster-queue-worker
            K8S_HOST: kubernetes
            K8S_DEPLOYMENT: buildcluster-queue-worker-bf1
        secrets:
            # Talking to Kubernetes
            - K8S_TOKEN

