---
executor:
    # Default executor
    plugin: k8s-vm
    k8s:
      pluginName: k8s
      exclusion:
        - 'rhel6'
      weightage: 0
      options:
        kubernetes:
            # The host or IP of the kubernetes cluster
            host: kubernetes.default
            # Privileged mode, default restricted, set to true for trusted container runtime use-case
            privileged: false
            automountServiceAccountToken: false
            dockerFeatureEnabled: false
            dnsPolicy: ClusterFirst
            resources:
                cpu:
                    # Number of cpu cores
                    micro: 1
                    low: 2
                    high: 6
                    turbo: 12
                    # upper bound for user custom cpu
                    max: 12
                memory:
                    # Memory in GB
                    micro: 1
                    low: 2
                    high: 12
                    turbo: 16
                    # upper bound for user custom memory
                    max: 16
            # Default build timeout for all builds in this cluster
            buildTimeout: 90
            # Default max build timeout
            maxBuildTimeout: 120
            # k8s node selectors for approprate pod scheduling
            nodeSelectors: {}
            preferredNodeSelectors: {}
            annotations: {}
            # support for kata-containers-as-a-runtimeclass
            runtimeClass: ""
        # Launcher image to use
        launchImage: screwdrivercd/launcher
        # Container tags to use
        launchVersion: stable
        # Circuit breaker config
        fusebox:
            breaker:
                # in milliseconds
                timeout: 10000
        # requestretry configs
        requestretry:
            # in milliseconds
            retryDelay: 3000
            maxAttempts: 5
    k8s-sandbox:
      pluginName: k8s
      options:
        kubernetes:
            # The host or IP of the kubernetes cluster
            host: kubernetes.default
            # Privileged mode, default restricted, set to true for trusted container runtime use-case
            privileged: false
            automountServiceAccountToken: false
            dockerFeatureEnabled: false
            resources:
                cpu:
                    # Number of cpu cores
                    micro: 1
                    low: 2
                    high: 6
                    turbo: 12
                    # upper bound for user custom cpu
                    max: 12
                memory:
                    # Memory in GB
                    micro: 1
                    low: 2
                    high: 12
                    turbo: 16
                    # upper bound for user custom memory
                    max: 16
            # Default build timeout for all builds in this cluster
            buildTimeout: 90
            # Default max build timeout
            maxBuildTimeout: 120
            # k8s node selectors for approprate pod scheduling
            nodeSelectors: {}
            preferredNodeSelectors: {}
            annotations: {}
            # support for kata-containers-as-a-runtimeclass
            runtimeClass: ""
        # Launcher image to use
        launchImage: screwdrivercd/launcher
        # Container tags to use
        launchVersion: stable
        # Circuit breaker config
        fusebox:
            breaker:
                # in milliseconds
                timeout: 10000
        # requestretry configs
        requestretry:
            # in milliseconds
            retryDelay: 3000
            maxAttempts: 5
    k8s-vm:
      pluginName: k8s-vm
      weightage: 0
      options:
        # Configuration of Docker
        kubernetes:
            # The host or IP of the kubernetes cluster
            host: kubernetes.default
            # Privileged mode, default restricted, set to true for trusted container runtime use-case
            privileged: false
            # Resources for build pod
            resources:
                cpu:
                    # Number of cpu cores
                    micro: 1
                    low: 2
                    high: 6
                    turbo: 12
                    # upper bound for user custom cpu
                    max: 12
                memory:
                    # Memory in GB
                    micro: 1
                    low: 2
                    high: 12
                    turbo: 16
                    # upper bound for user custom memory
                    max: 16
            # Default build timeout for all builds in this cluster
            buildTimeout: 90
            # Default max build timeout
            maxBuildTimeout: 120
            # k8s node selectors for approprate pod scheduling
            nodeSelectors: {}
            preferredNodeSelectors: {}
        # Launcher image to use
        launchImage: screwdrivercd/launcher
        # Launcher container tag to use
        launchVersion: stable
        # Circuit breaker config
        fusebox:
            breaker:
                # in milliseconds
                timeout: 10000
        # requestretry configs
        requestretry:
            # in milliseconds
            retryDelay: 3000
            maxAttempts: 5
#     jenkins:
#       options:
#         # Configuration of Jenkins
#         jenkins:
#             host: jenkins.default
#             port: 8080
#             username: screwdriver
#             password: "WOW-AN-EVEN-MORE-INSECURE-PASSWORD!!!!"
#             # Default build timeout (in minutes)
#             buildTimeout: 90
#             # Default max build timeout (in minutes)
#             maxBuildTimeout: 120

ecosystem:
    # Externally routable URL for the User Interface
    ui: https://cd.screwdriver.cd
    # Externally routable URL for the API
    api: https://api.screwdriver.cd
    # Externally routable URL for the Artifact Store
    store: https://store.screwdriver.cd
    # build cache strategies: s3, disk, with s3 as default option to store cache
    cache:
        strategy: "s3"
        path: "/"
        compress: false
        md5check: false
        max_size_mb: 0
        max_go_threads: 10000

rabbitmq:
    # Protocol for rabbitmq server, use amqps for ssl
    protocol: amqp
    # User to push to rabbitmq
    username: foo
    # Password to connect to rabbitmq cluster
    password: bar
    # Host of rabbitmq cluster
    host: 127.0.0.1
    # Port of rabbitmq cluster
    port: 5672
    # Virtual Host for queues
    vhost: /screwdriver
    # Connect Options
    connectOptions: { json: true, heartbeatIntervalInSeconds: 20, reconnectTimeInSeconds: 30 }
    # Queue name to consume from
    queue: test
    # Prefetch count
    prefetchCount: "20"
    # Queue options
    queueOptions: { durable: true, autodelete: false, deadLetterExchange: 'build', deadLetterRoutingKey: 'test_retry' }
    # Message reprocess limit - max retry for a message
    messageReprocessLimit: "3"
